// Меню блюд с рецептами
export const menuData = [
  {
    id: 1,
    name: "Классическая",
    description: "Хрустящая и сочная",
    price: 150,
    recipe: { chicken: 1, vegetables: 1, sauce: 1 },
    unlocked: true,
    unlocksAtLevel: 1,
  },
  {
    id: 2,
    name: "Королевская",
    description: "С двойной порцией мяса",
    price: 250,
    recipe: { chicken: 2, vegetables: 1, sauce: 1 },
    unlocked: false,
    unlocksAtLevel: 3,
  },
  {
    id: 3,
    name: "Овощная",
    description: "Для вегетарианцев",
    price: 120,
    recipe: { vegetables: 3, sauce: 1 },
    unlocked: false,
    unlocksAtLevel: 2,
  },
  {
    id: 4,
    name: "Острая",
    description: "Пожгите язык!",
    price: 200,
    recipe: { chicken: 1, vegetables: 1, sauce: 2 },
    unlocked: false,
    unlocksAtLevel: 4,
  },
  {
    id: 5,
    name: "Люкс",
    description: "Премиум с деликатесами",
    price: 400,
    recipe: { chicken: 3, vegetables: 2, sauce: 2 },
    unlocked: false,
    unlocksAtLevel: 6,
  },
];
