// Требования для повышения уровня
export const LEVEL_REQUIREMENTS = {
  1: { money: 1000, count: 10, title: "Новичок", reward: "Новое блюдо!" },
  2: { money: 3000, count: 30, title: "Помощник", reward: "Ускорение готовки" },
  3: { money: 8000, count: 75, title: "Шеф-повар", reward: "Новое блюдо + бонус цены" },
  4: { money: 20000, count: 150, title: "Мастер", reward: "Стажёр для пассивного дохода" },
  5: { money: 50000, count: 300, title: "Легенда", reward: "Премиум меню" },
  6: { money: 100000, count: 500, title: "Империя", reward: "Множитель дохода" },
};

// Апгрейды в магазине
export const SHOP_UPGRADES = [
  {
    id: "cheese_sauce",
    name: "Сырный соус",
    description: "Добавляет +50 сом к цене классической",
    type: "price",
    cost: 500,
    minLevel: 1,
    value: 50,
  },
  {
    id: "fast_hands",
    name: "Ловкие руки",
    description: "Ускоряет готовку на 2 секунды",
    type: "speed",
    cost: 1000,
    minLevel: 2,
    value: 2000,
  },
  {
    id: "apprentice",
    name: "Стажёр",
    description: "Пассивный доход 500 сом каждые 15 сек",
    type: "idle",
    cost: 5000,
    minLevel: 4,
    value: 0,
  },
  {
    id: "premium_meat",
    name: "Премиум мясо",
    description: "+100 сом ко всем блюдам с мясом",
    type: "price",
    cost: 3000,
    minLevel: 3,
    value: 100,
  },
  {
    id: "super_speed",
    name: "Супер-скорость",
    description: "Ускоряет готовку на 4 секунды",
    type: "speed",
    cost: 8000,
    minLevel: 4,
    value: 4000,
  },
  {
    id: "money_boost_x2",
    name: "Удваивающее зелье",
    description: "Увеличивает доход в 2 раза",
    type: "multiplier",
    cost: 15000,
    minLevel: 5,
    value: 2,
  },
  {
    id: "molecular_kitchen",
    name: "Молекулярная кухня",
    description: "+150 сом ко всем премиум блюдам",
    type: "price",
    cost: 10000,
    minLevel: 5,
    value: 150,
  },
  {
    id: "hyper_speed",
    name: "Гиперскорость",
    description: "Минимальная готовка (1 сек)",
    type: "speed",
    cost: 25000,
    minLevel: 6,
    value: 7000,
  },
];
